"""Rule-based curation of run exemplars (R1: no voltage-limit changes against the goal; R2: one per network/app/step)."""
from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
_spec = importlib.util.spec_from_file_location("curate_exemplars", ROOT / "rag" / "tools" / "curate_exemplars.py")
cur = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(cur)


def _block(net, goal, step, app="opflow"):
    return (f"[source: solver-certified AgentiGrid run | app: {app} | network: {net} | generated by: m | "
            f"harvested: 2026-09-28 | bus numbers: described in words]\nGoal: {goal}\nStep applied: {step}\n"
            f"Result: {app.upper()} converged, feasible, 0 violations.")


def test_r1_drops_voltage_limit_changes_the_goal_forbids():
    bad = _block("n1", "Relieve every overloaded line without shedding load or relaxing bus voltage limits",
                 "set_all_bus_vlimits(Vmin=0.95, Vmax=1.05); set_gen_dispatch on one generator bus", "pflow")
    bad2 = _block("n1", "Bring every bus voltage within 0.95-1.05 pu without shedding load or changing the voltage limits",
                  "set_all_bus_vlimits(Vmin=0.95, Vmax=1.05)", "pflow")
    ok_band = _block("n1", "Keep every bus voltage between 0.97 and 1.03 pu, without shedding load",
                     "set_all_bus_vlimits(Vmin=0.97, Vmax=1.03)")
    ok_cost = _block("n1", "Lower the cost without relaxing bus voltage limits", "set_gen_status on 4 offline generator buses")
    kept, dropped = cur.curate([bad, bad2, ok_band, ok_cost])
    assert kept == [ok_band, ok_cost] and [r for r, _ in dropped] == ["R1", "R1"]


def test_r2_keeps_one_per_network_app_step_with_the_stricter_goal():
    a = _block("n1", "Keep the band, without shedding load", "set_all_bus_vlimits(Vmin=0.97, Vmax=1.03)")
    b = _block("n1", "Keep the band, without shedding load or raising line ratings", "set_all_bus_vlimits(Vmin=0.97, Vmax=1.03)")
    c = _block("n2", "Keep the band, without shedding load", "set_all_bus_vlimits(Vmin=0.97, Vmax=1.03)")
    d = _block("n1", "Keep the band, without shedding load", "set_all_bus_vlimits(Vmin=0.97, Vmax=1.03)", "scopflow")
    kept, dropped = cur.curate([a, b, c, d])
    assert kept == [b, c, d] and [r for r, _ in dropped] == ["R2"]
    assert cur.curate(kept)[0] == kept                       # idempotent


def test_shipped_run_exemplars_are_curated():
    blocks = [b for b in (ROOT / "rag" / "corpus" / "exago_exemplars_from_runs.txt").read_text().split("\n\n") if b.strip()]
    kept, dropped = cur.curate(blocks)
    assert dropped == [] and len(kept) == 15
