"""Corpus v2: worked examples are network-neutral, and retrieved references carry a caution.

Background (2026-10-07): in a corrective-RAG run on case118, 63 of 68 skipped
commands targeted ACTIVSg500 buses that the model copied from retrieved examples.
"""

from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

ROOT = Path(__file__).resolve().parents[2]
CORPUS = ROOT / "rag" / "corpus"
CONCRETE_BUS = re.compile(r'"(?:bus|fbus|tbus)": *-?\d+')


def _load(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "rag" / "tools" / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


neutral = _load("exemplar_neutral")
schema = _load("rag_schema_exemplars")
guard = _load("corpus_guard")

V1_BLOCK = (
    "[source: solver-certified AgentiGrid run | app: opflow | network: case_ACTIVSg500 | "
    "generated by: m | harvested: 2026-09-28]\n"
    "Goal: Lower the cost\n"
    "Step applied: set_gen_status x4 on buses 435, 436, 125, 126 (status=1)\n"
    'Correct response (JSON): {"action": "modify", "mode": "fresh", "description": "x", "commands": '
    '[{"action": "set_gen_status", "bus": 435, "status": 1}, {"action": "set_gen_status", "bus": 436, "status": 1}, '
    '{"action": "set_gen_status", "bus": 125, "status": 1}, {"action": "set_gen_status", "bus": 126, "status": 1}]}\n'
    "Result: OPFLOW converged, feasible, 0 violations, objective 57,598.76 (-20.6% vs. base 72,578.30)."
)


def test_v1_run_exemplar_becomes_neutral_and_idempotent():
    v2 = neutral.convert_v1_block(V1_BLOCK)
    assert not CONCRETE_BUS.search(v2)
    assert not any(str(b) in v2 for b in (435, 436, 125, 126, "57,598", "72,578"))
    assert '"bus": <offline generator bus 1>' in v2 and "4 in this example" in v2
    assert "objective -20.6% vs. the base case of the source network" in v2
    assert "network: case_ACTIVSg500" in v2 and neutral.NEUTRAL_LABEL in v2
    assert neutral.PLACEHOLDER_NOTE in v2
    assert neutral.convert_v1_block(v2) == v2


def test_network_free_commands_are_unchanged():
    cmds = [{"action": "scale_all_loads", "factor": 1.05},
            {"action": "set_all_bus_vlimits", "Vmin": 0.95, "Vmax": 1.05}]
    assert neutral.neutral_commands_json(cmds) == json.dumps(cmds, separators=(", ", ": "))
    text = neutral.render_run_exemplar("[source: x]", "g", "fresh", cmds, "opflow", 1.0)
    assert "Placeholders" not in text      # no placeholder, no note


def test_generator_specific_values_become_placeholders_in_run_exemplars():
    cmds = [{"action": "set_gen_dispatch", "bus": 145, "Pg": 250.55}]
    text = neutral.render_run_exemplar("[source: x]", None, "fresh", cmds, "pflow", None)
    assert "145" not in text and "250.55" not in text
    assert '"bus": <generator bus>' in text and "Pmin and Pmax" in text


def test_text_substitution_keeps_decimals_and_other_numbers():
    cmds = [{"action": "set_shunt_susceptance", "bus": 44, "Bs": 25.0}]
    assert neutral.neutralize_text("Add 25 MVAr at bus 44.", cmds) == "Add 25 MVAr at <bus>."
    cmds = [{"action": "set_bus_vlimits", "bus": 12, "Vmin": 0.98, "Vmax": 1.02}]
    assert neutral.neutralize_text("Bus 12 band 0.98-1.02 pu", cmds) == "<bus> band 0.98-1.02 pu"


@pytest.mark.skipif(not (ROOT.parent / "datafiles" / "case118.m").exists(), reason="case118 not present")
def test_schema_exemplars_are_certified_concretely_but_rendered_neutrally():
    chunks = schema.build(ROOT.parent / "datafiles" / "case118.m")
    assert sum("applied on held-out case118" in c for c in chunks) >= 12   # certification unchanged
    for c in chunks:
        assert not CONCRETE_BUS.search(c), c
        assert not re.search(r"\b[Bb]us(es)? \d", c.replace(neutral.PLACEHOLDER_NOTE, "")), c


def test_guard_flags_concrete_bus_in_worked_examples():
    finds = guard.audit_text(V1_BLOCK, {"goals": set(), "networks": set()})
    assert [f["kind"] for f in finds] == ["concrete-bus"]
    assert guard.audit_text(neutral.convert_v1_block(V1_BLOCK), {"goals": set(), "networks": set()}) == []


def test_shipped_corpus_is_neutral_and_matches_its_manifest():
    from agentigrid.rag.corpus_hash import MANIFEST_NAME, corpus_hash
    manifest = json.loads((CORPUS / MANIFEST_NAME).read_text())
    digest, per_file = corpus_hash(CORPUS)
    assert digest == manifest["corpus_sha256"] and per_file == manifest["files"]
    none = {"goals": set(), "networks": set()}
    for f in guard.corpus_files(CORPUS):
        assert guard.audit_text(f.read_text(encoding="utf-8"), none) == [], f.name


def test_retrieved_references_carry_the_network_caution(tmp_path, monkeypatch):
    from agentigrid.engine import agent_loop as al
    from tests.agent_loop.test_agent_loop import (
        BASE_CASE, MockBackend, _has_base_case, _has_sample, _make_config, _make_llm_response,
        _make_sim_result, _objectives_response, _sample_stdout,
    )
    if not (_has_base_case and _has_sample):
        pytest.skip("base case or sample output not present")

    class _Ret:
        enabled = True

        def retrieve(self, q, k=None):
            return "[ref 1 | score 0.80] [source: x | bus numbers: placeholders] example"

        def describe(self):
            return {"mode": "basic", "enabled": True, "stats": {}}

    backend = MockBackend([_objectives_response(),
                           _make_llm_response({"action": "complete", "reasoning": "ok", "findings": {"summary": "ok"}})])
    with patch("agentigrid.engine.agent_loop.create_backend", return_value=backend), \
         patch("agentigrid.engine.agent_loop.SimulationExecutor") as ex, \
         patch("agentigrid.engine.agent_loop.build_retriever", return_value=_Ret()):
        ex.return_value = MagicMock(run=MagicMock(return_value=_make_sim_result(stdout=_sample_stdout(), success=True)))
        al.AgentLoopController(_make_config(tmp_path, max_iterations=2)).run(BASE_CASE, "Lower the cost")
    prompt = backend.calls[1][1]
    assert prompt.startswith("=== Section B: Reference Material (retrieved) ===\n" + al.RAG_REFERENCE_CAUTION)
