"""Corpus v3: worked examples are network-neutral, and retrieved references carry a caution.

Background (2026-10-07): in a corrective-RAG run on case118, 63 of 68 skipped
commands targeted ACTIVSg500 buses that the model copied from retrieved examples
(-> corpus v2, placeholders). The v2 pilot then showed models copying the JSON
placeholders literally (-> corpus v3: commands that name a bus are described in
words, with no JSON template and no angle-bracket token).
"""

from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

ROOT = Path(__file__).resolve().parents[2]
CORPUS = ROOT / "rag" / "corpus"
CONCRETE_BUS = re.compile(r'"(?:bus|fbus|tbus)": *-?\d+')
ANGLE = re.compile(r"<[^>\n]+>")


def _load(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "rag" / "tools" / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


neutral = _load("exemplar_neutral")
schema = _load("rag_schema_exemplars")
guard = _load("corpus_guard")

V1_BLOCK = (
    "[source: solver-certified AgentiGrid run | app: opflow | network: case_ACTIVSg500 | "
    "generated by: m | harvested: 2026-09-28]\n"
    "Goal: Lower the cost\n"
    "Step applied: set_gen_status x4 on buses 435, 436, 125, 126 (status=1)\n"
    'Correct response (JSON): {"action": "modify", "mode": "fresh", "description": "x", "commands": '
    '[{"action": "set_gen_status", "bus": 435, "status": 1}, {"action": "set_gen_status", "bus": 436, "status": 1}, '
    '{"action": "set_gen_status", "bus": 125, "status": 1}, {"action": "set_gen_status", "bus": 126, "status": 1}]}\n'
    "Result: OPFLOW converged, feasible, 0 violations, objective 57,598.76 (-20.6% vs. base 72,578.30)."
)


def test_v1_run_exemplar_becomes_words_and_idempotent():
    v3 = neutral.convert_v1_block(V1_BLOCK)
    assert not CONCRETE_BUS.search(v3) and not ANGLE.search(v3)
    assert "Correct response (JSON)" not in v3            # no template to copy
    assert not any(str(b) in v3 for b in (435, 436, 125, 126, "57,598", "72,578"))
    assert "Step applied: set_gen_status on 4 offline generator buses (status=1)" in v3
    assert ("one set_gen_status command per offline generator bus (4 in this example), each with "
            '"bus" set to a bus number listed on the "Offline generators (status=0)" line') in v3
    assert "If that line says (none), this step does not apply" in v3
    assert "objective -20.6% vs. the base case of the source network" in v3
    assert "network: case_ACTIVSg500" in v3 and neutral.NEUTRAL_LABEL in v3
    assert neutral.PLACEHOLDER_NOTE in v3
    assert neutral.convert_v1_block(v3) == v3


def test_v2_blocks_are_refused():
    v2 = V1_BLOCK.replace("2026-09-28]", "2026-09-28 | " + neutral.V2_LABEL + "]")
    with pytest.raises(ValueError):
        neutral.convert_v1_block(v2)


def test_network_free_commands_keep_their_json():
    cmds = [{"action": "scale_all_loads", "factor": 1.05},
            {"action": "set_all_bus_vlimits", "Vmin": 0.95, "Vmax": 1.05}]
    text = neutral.render_run_exemplar("[source: x]", "g", "fresh", cmds, "opflow", 1.0)
    assert '"commands": ' + json.dumps(cmds, separators=(", ", ": ")) in text
    assert "Correct response (JSON)" in text and "How to write" not in text
    assert neutral.PLACEHOLDER_NOTE not in text


def test_generator_specific_values_are_described():
    cmds = [{"action": "set_gen_dispatch", "bus": 145, "Pg": 250.55}]
    text = neutral.render_run_exemplar("[source: x]", None, "fresh", cmds, "pflow", None)
    assert "145" not in text and "250.55" not in text and not ANGLE.search(text)
    assert '"bus" set to the bus number of a generator of THIS network' in text
    assert "between that generator's Pmin and Pmax" in text


def test_mixed_list_keeps_network_free_json_and_describes_the_rest():
    cmds = [{"action": "set_all_bus_vlimits", "Vmin": 0.95, "Vmax": 1.05},
            {"action": "set_branch_status", "fbus": 8, "tbus": 5, "status": 0}]
    text = neutral.commands_in_words(cmds)
    assert text.startswith('{"action": "set_all_bus_vlimits", "Vmin": 0.95, "Vmax": 1.05}; ')
    assert '"fbus" set to the from-bus number of a branch' in text and '"tbus" set to the to-bus number' in text


def test_text_substitution_keeps_decimals_and_other_numbers():
    cmds = [{"action": "set_shunt_susceptance", "bus": 44, "Bs": 25.0}]
    assert neutral.neutralize_text("Add 25 MVAr at bus 44.", cmds) == "Add 25 MVAr at <bus>."
    assert neutral.placeholders_to_words("Add 25 MVAr at <bus>.") == "Add 25 MVAr at a bus."
    cmds = [{"action": "set_bus_vlimits", "bus": 12, "Vmin": 0.98, "Vmax": 1.02}]
    assert neutral.neutralize_text("Bus 12 band 0.98-1.02 pu", cmds) == "<bus> band 0.98-1.02 pu"
    assert neutral.placeholders_to_words("between buses <from bus> and <to bus>") == "between two buses"


@pytest.mark.skipif(not (ROOT.parent / "datafiles" / "case118.m").exists(), reason="case118 not present")
def test_schema_exemplars_are_certified_concretely_but_rendered_neutrally():
    chunks = schema.build(ROOT.parent / "datafiles" / "case118.m")
    assert sum("applied on held-out case118" in c for c in chunks) >= 12   # certification unchanged
    for c in chunks:
        assert not CONCRETE_BUS.search(c) and not ANGLE.search(c), c
        assert not re.search(r"\b[Bb]us(es)? \d", c), c
        if '"bus"' in c or '"fbus"' in c:
            assert "How to write the response:" in c and "Correct response (JSON)" not in c, c


def test_guard_flags_concrete_bus_and_json_placeholders():
    none = {"goals": set(), "networks": set()}
    assert [f["kind"] for f in guard.audit_text(V1_BLOCK, none)] == ["concrete-bus"]
    v2_line = ('[source: solver-certified AgentiGrid run | x]\n'
               'Correct response (JSON): {"commands": [{"action": "set_gen_status", "bus": <bus>, "status": 1}]}')
    assert [f["kind"] for f in guard.audit_text(v2_line, none)] == ["json-placeholder"]
    assert guard.audit_text(neutral.convert_v1_block(V1_BLOCK), none) == []


def test_shipped_corpus_is_neutral_and_matches_its_manifest():
    from agentigrid.rag.corpus_hash import MANIFEST_NAME, corpus_hash
    manifest = json.loads((CORPUS / MANIFEST_NAME).read_text())
    digest, per_file = corpus_hash(CORPUS)
    assert digest == manifest["corpus_sha256"] and per_file == manifest["files"]
    none = {"goals": set(), "networks": set()}
    for f in guard.corpus_files(CORPUS):
        assert guard.audit_text(f.read_text(encoding="utf-8"), none) == [], f.name


def test_retrieved_references_carry_the_network_caution(tmp_path, monkeypatch):
    from agentigrid.engine import agent_loop as al
    from tests.agent_loop.test_agent_loop import (
        BASE_CASE, MockBackend, _has_base_case, _has_sample, _make_config, _make_llm_response,
        _make_sim_result, _objectives_response, _sample_stdout,
    )
    if not (_has_base_case and _has_sample):
        pytest.skip("base case or sample output not present")

    class _Ret:
        enabled = True

        def retrieve(self, q, k=None):
            return "[ref 1 | score 0.80] [source: x | bus numbers: described in words] example"

        def describe(self):
            return {"mode": "basic", "enabled": True, "stats": {}}

    backend = MockBackend([_objectives_response(),
                           _make_llm_response({"action": "complete", "reasoning": "ok", "findings": {"summary": "ok"}})])
    with patch("agentigrid.engine.agent_loop.create_backend", return_value=backend), \
         patch("agentigrid.engine.agent_loop.SimulationExecutor") as ex, \
         patch("agentigrid.engine.agent_loop.build_retriever", return_value=_Ret()):
        ex.return_value = MagicMock(run=MagicMock(return_value=_make_sim_result(stdout=_sample_stdout(), success=True)))
        al.AgentLoopController(_make_config(tmp_path, max_iterations=2)).run(BASE_CASE, "Lower the cost")
    prompt = backend.calls[1][1]
    assert prompt.startswith("=== Section B: Reference Material (retrieved) ===\n" + al.RAG_REFERENCE_CAUTION)
